-- Actualiza fecha_nacimiento usando CUMPLEAÑOS 2026.xlsx como fuente correcta
-- Ejecutar en MySQL Workbench sobre gestio_humana.
USE gestio_humana;
START TRANSACTION;

-- ENERO: AYALA PEÑARANDA CRISTIAN DAVID / LINEA DE SACRIFICIO -> 02/01/2003
UPDATE empleado SET fecha_nacimiento = '02/01/2003' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('AYALA PEÑARANDA CRISTIAN DAVID');
-- ENERO: RODRIGUEZ RUIZ ALEXANDER / PLANEACION -> 02/01/1989
UPDATE empleado SET fecha_nacimiento = '02/01/1989' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('RODRIGUEZ RUIZ ALEXANDER');
-- ENERO: PABON SERRANO ANDERSON / LINEA DE SACRIFICIO -> 03/01/2002
UPDATE empleado SET fecha_nacimiento = '03/01/2002' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('PABON SERRANO ANDERSON');
-- ENERO: SANTOS TORRA CARLOS ALBERTO / LINEA DESPOSTE -> 04/01/1984
UPDATE empleado SET fecha_nacimiento = '04/01/1984' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('SANTOS TORRA CARLOS ALBERTO');
-- ENERO: SANCHEZ URIBE EDIVAN / LOGISTICA -> 04/01/2000
UPDATE empleado SET fecha_nacimiento = '04/01/2000' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('SANCHEZ URIBE EDIVAN');
-- ENERO: PIÑERES ROCHA CHRISTIAN CAMILO / LINEA DESPOSTE -> 05/01/1999
UPDATE empleado SET fecha_nacimiento = '05/01/1999' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('PIÑERES ROCHA CHRISTIAN CAMILO');
-- ENERO: GALEANO ROA DANIEL ESTIVEN / DIRECCION DPTO CALIDAD -> 05/01/2003
UPDATE empleado SET fecha_nacimiento = '05/01/2003' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('GALEANO ROA DANIEL ESTIVEN');
-- ENERO: CASTILLO MARIN JOSE LUIS / SUBPRODUCTOS COMESTIBLES -> 05/01/1999
UPDATE empleado SET fecha_nacimiento = '05/01/1999' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('CASTILLO MARIN JOSE LUIS');
-- ENERO: AGUDELO CORTES OSCAR MAURICIO / LOGISTICA DESPOSTE -> 07/01/2003
UPDATE empleado SET fecha_nacimiento = '07/01/2003' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('AGUDELO CORTES OSCAR MAURICIO');
-- ENERO: SANCHEZ RODRIGUEZ EUDY JOSE / LOGISTICA -> 07/01/1996
UPDATE empleado SET fecha_nacimiento = '07/01/1996' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('SANCHEZ RODRIGUEZ EUDY JOSE');
-- ENERO: GONZALEZ DELGADO EDUAR VIRLEY / LINEA DESPOSTE -> 12/01/1985
UPDATE empleado SET fecha_nacimiento = '12/01/1985' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('GONZALEZ DELGADO EDUAR VIRLEY');
-- ENERO: CARDENAS CAICEDO URIEL / LINEA DE SACRIFICIO -> 13/01/1981
UPDATE empleado SET fecha_nacimiento = '13/01/1981' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('CARDENAS CAICEDO URIEL');
-- ENERO: OLIVERA FLOREZ JOSE GABRIEL / SUBPRODUCTOS COMESTIBLES -> 14/01/1985
UPDATE empleado SET fecha_nacimiento = '14/01/1985' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('OLIVERA FLOREZ JOSE GABRIEL');
-- ENERO: CARREÑO MENDOZA JUAN PABLO / TECNOLOGIA -> 15/01/2000
UPDATE empleado SET fecha_nacimiento = '15/01/2000' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('CARREÑO MENDOZA JUAN PABLO');
-- ENERO: RINCON MENDOZA DUBIAN ERNEY / LIMPIEZA Y DESINFECCION -> 17/01/1997
UPDATE empleado SET fecha_nacimiento = '17/01/1997' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('RINCON MENDOZA DUBIAN ERNEY');
-- ENERO: LOZADA ORTIZ OLIVER SEBASTIAN / LOGISTICA DESPOSTE -> 20/01/1994
UPDATE empleado SET fecha_nacimiento = '20/01/1994' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('LOZADA ORTIZ OLIVER SEBASTIAN');
-- ENERO: COTE HERNANDEZ MARIA CAMILA / INVIMA -> 21/01/2000
UPDATE empleado SET fecha_nacimiento = '21/01/2000' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('COTE HERNANDEZ MARIA CAMILA');
-- ENERO: RUEDA TARAZONA JUAN MANUEL / RECEPCION Y PESAJE -> 24/01/2003
UPDATE empleado SET fecha_nacimiento = '24/01/2003' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('RUEDA TARAZONA JUAN MANUEL');
-- ENERO: AGON PEDRAZA JAIRO FABIAN / SUBPRODUCTOS COMESTIBLES -> 26/01/2001
UPDATE empleado SET fecha_nacimiento = '26/01/2001' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('AGON PEDRAZA JAIRO FABIAN');
-- ENERO: PACHECO MANRIQUE ANDRES FELIPE / LINEA DE SACRIFICIO -> 26/01/1998
UPDATE empleado SET fecha_nacimiento = '26/01/1998' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('PACHECO MANRIQUE ANDRES FELIPE');
-- ENERO: MOGOLLON TOLOZA JESUS DAVID / LIMPIEZA Y DESINFECCION -> 27/01/1998
UPDATE empleado SET fecha_nacimiento = '27/01/1998' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('MOGOLLON TOLOZA JESUS DAVID');
-- ENERO: GOMEZ MARTINEZ NIDIA ROCIO / DIRECCION DPTO JURIDICO Y GESTION HUMANA -> 28/01/1980
UPDATE empleado SET fecha_nacimiento = '28/01/1980' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('GOMEZ MARTINEZ NIDIA ROCIO');
-- ENERO: GARCIA LINARES FREILEN BRANYAN / LOGISTICA -> 29/01/1993
UPDATE empleado SET fecha_nacimiento = '29/01/1993' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('GARCIA LINARES FREILEN BRANYAN');
-- ENERO: ROCHA FUENTES JUAN DAVID / LOGISTICA DESPOSTE -> 31/01/2002
UPDATE empleado SET fecha_nacimiento = '31/01/2002' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('ROCHA FUENTES JUAN DAVID');
-- ENERO: Apellidos y Nombres / Area -> Fecha de Nacimiento
UPDATE empleado SET fecha_nacimiento = 'Fecha de Nacimiento' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('Apellidos y Nombres');
-- ENERO: AYALA PEÑARANDA CRISTIAN DAVID / LINEA DE SACRIFICIO -> 02/01/2003
UPDATE empleado SET fecha_nacimiento = '02/01/2003' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('AYALA PEÑARANDA CRISTIAN DAVID');
-- ENERO: RODRIGUEZ RUIZ ALEXANDER / PLANEACION -> 02/01/1989
UPDATE empleado SET fecha_nacimiento = '02/01/1989' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('RODRIGUEZ RUIZ ALEXANDER');
-- ENERO: PABON SERRANO ANDERSON / LINEA DE SACRIFICIO -> 03/01/2002
UPDATE empleado SET fecha_nacimiento = '03/01/2002' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('PABON SERRANO ANDERSON');
-- ENERO: SANTOS TORRA CARLOS ALBERTO / LINEA DESPOSTE -> 04/01/1984
UPDATE empleado SET fecha_nacimiento = '04/01/1984' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('SANTOS TORRA CARLOS ALBERTO');
-- ENERO: SANCHEZ URIBE EDIVAN / LOGISTICA -> 04/01/2000
UPDATE empleado SET fecha_nacimiento = '04/01/2000' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('SANCHEZ URIBE EDIVAN');
-- ENERO: PIÑERES ROCHA CHRISTIAN CAMILO / LINEA DESPOSTE -> 05/01/1999
UPDATE empleado SET fecha_nacimiento = '05/01/1999' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('PIÑERES ROCHA CHRISTIAN CAMILO');
-- ENERO: GALEANO ROA DANIEL ESTIVEN / DIRECCION DPTO CALIDAD -> 05/01/2003
UPDATE empleado SET fecha_nacimiento = '05/01/2003' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('GALEANO ROA DANIEL ESTIVEN');
-- ENERO: CASTILLO MARIN JOSE LUIS / SUBPRODUCTOS COMESTIBLES -> 05/01/1999
UPDATE empleado SET fecha_nacimiento = '05/01/1999' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('CASTILLO MARIN JOSE LUIS');
-- ENERO: AGUDELO CORTES OSCAR MAURICIO / LOGISTICA DESPOSTE -> 07/01/2003
UPDATE empleado SET fecha_nacimiento = '07/01/2003' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('AGUDELO CORTES OSCAR MAURICIO');
-- ENERO: SANCHEZ RODRIGUEZ EUDY JOSE / LOGISTICA -> 07/01/1996
UPDATE empleado SET fecha_nacimiento = '07/01/1996' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('SANCHEZ RODRIGUEZ EUDY JOSE');
-- ENERO: GONZALEZ DELGADO EDUAR VIRLEY / LINEA DESPOSTE -> 12/01/1985
UPDATE empleado SET fecha_nacimiento = '12/01/1985' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('GONZALEZ DELGADO EDUAR VIRLEY');
-- ENERO: CARDENAS CAICEDO URIEL / LINEA DE SACRIFICIO -> 13/01/1981
UPDATE empleado SET fecha_nacimiento = '13/01/1981' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('CARDENAS CAICEDO URIEL');
-- ENERO: OLIVERA FLOREZ JOSE GABRIEL / SUBPRODUCTOS COMESTIBLES -> 14/01/1985
UPDATE empleado SET fecha_nacimiento = '14/01/1985' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('OLIVERA FLOREZ JOSE GABRIEL');
-- ENERO: CARREÑO MENDOZA JUAN PABLO / TECNOLOGIA -> 15/01/2000
UPDATE empleado SET fecha_nacimiento = '15/01/2000' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('CARREÑO MENDOZA JUAN PABLO');
-- ENERO: RINCON MENDOZA DUBIAN ERNEY / LIMPIEZA Y DESINFECCION -> 17/01/1997
UPDATE empleado SET fecha_nacimiento = '17/01/1997' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('RINCON MENDOZA DUBIAN ERNEY');
-- ENERO: LOZADA ORTIZ OLIVER SEBASTIAN / LOGISTICA DESPOSTE -> 20/01/1994
UPDATE empleado SET fecha_nacimiento = '20/01/1994' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('LOZADA ORTIZ OLIVER SEBASTIAN');
-- ENERO: COTE HERNANDEZ MARIA CAMILA / INVIMA -> 21/01/2000
UPDATE empleado SET fecha_nacimiento = '21/01/2000' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('COTE HERNANDEZ MARIA CAMILA');
-- ENERO: RUEDA TARAZONA JUAN MANUEL / RECEPCION Y PESAJE -> 24/01/2003
UPDATE empleado SET fecha_nacimiento = '24/01/2003' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('RUEDA TARAZONA JUAN MANUEL');
-- ENERO: AGON PEDRAZA JAIRO FABIAN / SUBPRODUCTOS COMESTIBLES -> 26/01/2001
UPDATE empleado SET fecha_nacimiento = '26/01/2001' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('AGON PEDRAZA JAIRO FABIAN');
-- ENERO: PACHECO MANRIQUE ANDRES FELIPE / LINEA DE SACRIFICIO -> 26/01/1998
UPDATE empleado SET fecha_nacimiento = '26/01/1998' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('PACHECO MANRIQUE ANDRES FELIPE');
-- ENERO: MOGOLLON TOLOZA JESUS DAVID / LIMPIEZA Y DESINFECCION -> 27/01/1998
UPDATE empleado SET fecha_nacimiento = '27/01/1998' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('MOGOLLON TOLOZA JESUS DAVID');
-- ENERO: GOMEZ MARTINEZ NIDIA ROCIO / DIRECCION DPTO JURIDICO Y GESTION HUMANA -> 28/01/1980
UPDATE empleado SET fecha_nacimiento = '28/01/1980' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('GOMEZ MARTINEZ NIDIA ROCIO');
-- ENERO: GARCIA LINARES FREILEN BRANYAN / LOGISTICA -> 29/01/1993
UPDATE empleado SET fecha_nacimiento = '29/01/1993' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('GARCIA LINARES FREILEN BRANYAN');
-- ENERO: ROCHA FUENTES JUAN DAVID / LOGISTICA DESPOSTE -> 31/01/2002
UPDATE empleado SET fecha_nacimiento = '31/01/2002' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('ROCHA FUENTES JUAN DAVID');
-- FEBRERO: SILVERA FLORES LUIGY OBRAYAN / SUBPRODUCTOS COMESTIBLES -> 01/02/2002
UPDATE empleado SET fecha_nacimiento = '01/02/2002' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('SILVERA FLORES LUIGY OBRAYAN');
-- FEBRERO: RONCALLO RADA JOSE LUIS / LINEA DE SACRIFICIO -> 01/02/1995
UPDATE empleado SET fecha_nacimiento = '01/02/1995' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('RONCALLO RADA JOSE LUIS');
-- FEBRERO: GARCIA ANDRADES VICTOR ALFONSO / RECEPCION Y PESAJE -> 02/02/1993
UPDATE empleado SET fecha_nacimiento = '02/02/1993' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('GARCIA ANDRADES VICTOR ALFONSO');
-- FEBRERO: LOBO VELASQUEZ LUIS HERNANDO / LIMPIEZA Y DESINFECCION -> 03/02/2000
UPDATE empleado SET fecha_nacimiento = '03/02/2000' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('LOBO VELASQUEZ LUIS HERNANDO');
-- FEBRERO: ARIAS PARADA JHONATAN DAVID / DIRECCION DPTO CALIDAD -> 04/02/2001
UPDATE empleado SET fecha_nacimiento = '04/02/2001' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('ARIAS PARADA JHONATAN DAVID');
-- FEBRERO: SOTO MATEUS WILMAR / RECEPCION Y PESAJE -> 04/02/1980
UPDATE empleado SET fecha_nacimiento = '04/02/1980' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('SOTO MATEUS WILMAR');
-- FEBRERO: HERNANDEZ DURAN PEDRO JOSE / LIMPIEZA Y DESINFECCION -> 05/02/1995
UPDATE empleado SET fecha_nacimiento = '05/02/1995' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('HERNANDEZ DURAN PEDRO JOSE');
-- FEBRERO: CAMACHO ARENAS EMERSON ALBERTO / SUBPRODUCTOS COMESTIBLES -> 05/02/2000
UPDATE empleado SET fecha_nacimiento = '05/02/2000' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('CAMACHO ARENAS EMERSON ALBERTO');
-- FEBRERO: RIVERA COLMENARES JHON NEIDER / SUBPRODUCTOS COMESTIBLES -> 05/02/1993
UPDATE empleado SET fecha_nacimiento = '05/02/1993' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('RIVERA COLMENARES JHON NEIDER');
-- FEBRERO: RUBIANO LEMUS YUDY ANDREA / DIRECCION DPTO CALIDAD -> 07/02/1985
UPDATE empleado SET fecha_nacimiento = '07/02/1985' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('RUBIANO LEMUS YUDY ANDREA');
-- FEBRERO: JAIMES DIAZ ALEXANDER / SUBPRODUCTOS COMESTIBLES -> 09/02/1982
UPDATE empleado SET fecha_nacimiento = '09/02/1982' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('JAIMES DIAZ ALEXANDER');
-- FEBRERO: MANTILLA SAAVEDRA YEVINSON RENE / LINEA DE SACRIFICIO -> 10/02/2007
UPDATE empleado SET fecha_nacimiento = '10/02/2007' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('MANTILLA SAAVEDRA YEVINSON RENE');
-- FEBRERO: MEDINA CARLOS SNEYDER / CONTABILIDAD -> 10/02/1990
UPDATE empleado SET fecha_nacimiento = '10/02/1990' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('MEDINA CARLOS SNEYDER');
-- FEBRERO: ALVAREZ ARVELO ROKY DAVID / TESORERIA -> 10/02/1987
UPDATE empleado SET fecha_nacimiento = '10/02/1987' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('ALVAREZ ARVELO ROKY DAVID');
-- FEBRERO: PONTON PONTON EVER MAURICIO / LINEA DE SACRIFICIO -> 10/02/1997
UPDATE empleado SET fecha_nacimiento = '10/02/1997' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('PONTON PONTON EVER MAURICIO');
-- FEBRERO: SAAVEDRA SANTISTEBAN LAURA MELISSA / COMPRAS -> 11/02/1987
UPDATE empleado SET fecha_nacimiento = '11/02/1987' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('SAAVEDRA SANTISTEBAN LAURA MELISSA');
-- FEBRERO: GONZALEZ MIELES ADALGIZA / CONTABILIDAD -> 12/02/1992
UPDATE empleado SET fecha_nacimiento = '12/02/1992' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('GONZALEZ MIELES ADALGIZA');
-- FEBRERO: SANTERO SUAREZ EVELIO ISAAC / LOGISTICA -> 14/02/1999
UPDATE empleado SET fecha_nacimiento = '14/02/1999' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('SANTERO SUAREZ EVELIO ISAAC');
-- FEBRERO: SILVA QUIJANO ANDERSON JULIAN / SUBPRODUCTOS COMESTIBLES -> 14/02/2000
UPDATE empleado SET fecha_nacimiento = '14/02/2000' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('SILVA QUIJANO ANDERSON JULIAN');
-- FEBRERO: SUAREZ JAIMES ALBERTO / LINEA DE SACRIFICIO -> 15/02/1985
UPDATE empleado SET fecha_nacimiento = '15/02/1985' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('SUAREZ JAIMES ALBERTO');
-- FEBRERO: TOLOZA JAIMES CLEIVER ERMIDES / LINEA DE SACRIFICIO -> 15/02/1991
UPDATE empleado SET fecha_nacimiento = '15/02/1991' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('TOLOZA JAIMES CLEIVER ERMIDES');
-- FEBRERO: RINCON TORRES JAVIER ENRIQUE / SUBPRODUCTOS COMESTIBLES -> 16/02/1984
UPDATE empleado SET fecha_nacimiento = '16/02/1984' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('RINCON TORRES JAVIER ENRIQUE');
-- FEBRERO: PEÑA ARENAS PEDRO ARMANDO / L&D DESPOSTE -> 16/02/2001
UPDATE empleado SET fecha_nacimiento = '16/02/2001' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('PEÑA ARENAS PEDRO ARMANDO');
-- FEBRERO: AMAYA TASCO JORGE ALEXIS / LINEA DESPOSTE -> 18/02/1989
UPDATE empleado SET fecha_nacimiento = '18/02/1989' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('AMAYA TASCO JORGE ALEXIS');
-- FEBRERO: GUALDRON CASTELLANOS NELSON ENRIQUE / LOGISTICA -> 21/02/1985
UPDATE empleado SET fecha_nacimiento = '21/02/1985' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('GUALDRON CASTELLANOS NELSON ENRIQUE');
-- FEBRERO: HERNANDEZ URZOLA ROBERTO CARLOS / DIRECCION DPTO COMERCIAL -> 22/02/1972
UPDATE empleado SET fecha_nacimiento = '22/02/1972' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('HERNANDEZ URZOLA ROBERTO CARLOS');
-- FEBRERO: MARQUEZ RODRIGUEZ SILVIA JULIANA / GESTION HUMANA -> 23/02/1995
UPDATE empleado SET fecha_nacimiento = '23/02/1995' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('MARQUEZ RODRIGUEZ SILVIA JULIANA');
-- FEBRERO: SEGURA BARRERA MARIA FILOMENA / DIRECCION DPTO CALIDAD -> 23/02/1987
UPDATE empleado SET fecha_nacimiento = '23/02/1987' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('SEGURA BARRERA MARIA FILOMENA');
-- FEBRERO: CORREA MANRIQUE LEONARDO / LIMPIEZA Y DESINFECCION -> 26/02/1990
UPDATE empleado SET fecha_nacimiento = '26/02/1990' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('CORREA MANRIQUE LEONARDO');
-- FEBRERO: RODRIGUEZ HERNANDEZ ANDRES MAURICIO / LOGISTICA -> 27/02/1992
UPDATE empleado SET fecha_nacimiento = '27/02/1992' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('RODRIGUEZ HERNANDEZ ANDRES MAURICIO');
-- FEBRERO: RIVERA GOMEZ CAMILO ANDRES / SUBPRODUCTOS COMESTIBLES -> 28/02/2003
UPDATE empleado SET fecha_nacimiento = '28/02/2003' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('RIVERA GOMEZ CAMILO ANDRES');
-- MARZO: MORENO MARTINEZ JESUS ANTONIO / SUBPRODUCTOS COMESTIBLES -> 01/03/1988
UPDATE empleado SET fecha_nacimiento = '01/03/1988' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('MORENO MARTINEZ JESUS ANTONIO');
-- MARZO: SANABRIA TORRES YEBERSON LEANDRO / LINEA DE SACRIFICIO -> 01/03/1996
UPDATE empleado SET fecha_nacimiento = '01/03/1996' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('SANABRIA TORRES YEBERSON LEANDRO');
-- MARZO: GARCIA ANDRADES VICTOR ALFONSO / RECEPCION Y PESAJE -> 03/03/1993
UPDATE empleado SET fecha_nacimiento = '03/03/1993' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('GARCIA ANDRADES VICTOR ALFONSO');
-- MARZO: MIRANDA HERNANDEZ KAREN JOHANNA / CALIDAD DESPOSTE -> 04/03/2000
UPDATE empleado SET fecha_nacimiento = '04/03/2000' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('MIRANDA HERNANDEZ KAREN JOHANNA');
-- MARZO: DELGADO FLOREZ GABRIEL / LINEA DE SACRIFICIO -> 05/03/1985
UPDATE empleado SET fecha_nacimiento = '05/03/1985' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('DELGADO FLOREZ GABRIEL');
-- MARZO: MEJIA GUERRERO FRANCISCO / PTAR -> 07/03/1966
UPDATE empleado SET fecha_nacimiento = '07/03/1966' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('MEJIA GUERRERO FRANCISCO');
-- MARZO: CARRILLO GONZALEZ SARAI DANIELA / TESORERIA -> 08/03/2002
UPDATE empleado SET fecha_nacimiento = '08/03/2002' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('CARRILLO GONZALEZ SARAI DANIELA');
-- MARZO: MANZANO LIZARAZO MANZUR NAIN / L&D DESPOSTE -> 10/03/1992
UPDATE empleado SET fecha_nacimiento = '10/03/1992' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('MANZANO LIZARAZO MANZUR NAIN');
-- MARZO: DURAN PUENTES LAUDID / CONTABILIDAD -> 11/03/2002
UPDATE empleado SET fecha_nacimiento = '11/03/2002' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('DURAN PUENTES LAUDID');
-- MARZO: MORENO GAMA JUAN CARLOS / RECEPCION Y PESAJE -> 15/03/1987
UPDATE empleado SET fecha_nacimiento = '15/03/1987' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('MORENO GAMA JUAN CARLOS');
-- MARZO: LOPEZ PEREZ BRAYAN ENRIQUE / DIRECCION DPTO CALIDAD -> 17/03/1996
UPDATE empleado SET fecha_nacimiento = '17/03/1996' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('LOPEZ PEREZ BRAYAN ENRIQUE');
-- MARZO: ESPITIA LANDAZABAL JAHIR FABIAN / SUBPRODUCTOS COMESTIBLES -> 20/03/1996
UPDATE empleado SET fecha_nacimiento = '20/03/1996' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('ESPITIA LANDAZABAL JAHIR FABIAN');
-- MARZO: AFANADOR PINEDA NELSON / LINEA DE SACRIFICIO -> 22/03/1992
UPDATE empleado SET fecha_nacimiento = '22/03/1992' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('AFANADOR PINEDA NELSON');
-- MARZO: VARGAS OSSES JHON ELKIN / LOGISTICA -> 25/03/1990
UPDATE empleado SET fecha_nacimiento = '25/03/1990' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('VARGAS OSSES JHON ELKIN');
-- MARZO: ROMERO PEDRAZA SERGIO OMAR / LINEA DE SACRIFICIO -> 25/03/1993
UPDATE empleado SET fecha_nacimiento = '25/03/1993' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('ROMERO PEDRAZA SERGIO OMAR');
-- MARZO: LOPEZ DELGADO ELICEO / PTAP -> 26/03/1985
UPDATE empleado SET fecha_nacimiento = '26/03/1985' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('LOPEZ DELGADO ELICEO');
-- MARZO: ROBLES BELEÑO RONALDO / LINEA DE SACRIFICIO -> 27/03/1998
UPDATE empleado SET fecha_nacimiento = '27/03/1998' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('ROBLES BELEÑO RONALDO');
-- MARZO: MARQUEZ ZERPA YAMPIER JESUS / SUBPRODUCTOS COMESTIBLES -> 30/03/1997
UPDATE empleado SET fecha_nacimiento = '30/03/1997' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('MARQUEZ ZERPA YAMPIER JESUS');
-- MARZO: AGUILAR SAAVEDRA LUIS DAVID / LINEA DE SACRIFICIO -> 31/03/2004
UPDATE empleado SET fecha_nacimiento = '31/03/2004' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('AGUILAR SAAVEDRA LUIS DAVID');
-- ABRIL: PARADA SILVA ANDREY ALIRIO / LIMPIEZA Y DESINFECCION -> 05/04/1996
UPDATE empleado SET fecha_nacimiento = '05/04/1996' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('PARADA SILVA ANDREY ALIRIO');
-- ABRIL: BRAVO MARTINEZ DUBAN DAVID / LINEA DE SACRIFICIO -> 05/04/1998
UPDATE empleado SET fecha_nacimiento = '05/04/1998' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('BRAVO MARTINEZ DUBAN DAVID');
-- ABRIL: FERNANDEZ SOLANO ELIO ANTONIO / SUBPRODUCTOS COMESTIBLES -> 07/04/1988
UPDATE empleado SET fecha_nacimiento = '07/04/1988' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('FERNANDEZ SOLANO ELIO ANTONIO');
-- ABRIL: AYALA GUTIERREZ JOHN JAIRO / COMPRAS -> 07/04/1987
UPDATE empleado SET fecha_nacimiento = '07/04/1987' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('AYALA GUTIERREZ JOHN JAIRO');
-- ABRIL: MENDEZ SERRANO ZAIRA YOLIMA / COMPRAS -> 08/04/1980
UPDATE empleado SET fecha_nacimiento = '08/04/1980' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('MENDEZ SERRANO ZAIRA YOLIMA');
-- ABRIL: BLANCO CAVIEDES JOHN EDWIN / LIMPIEZA Y DESINFECCION -> 11/04/1986
UPDATE empleado SET fecha_nacimiento = '11/04/1986' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('BLANCO CAVIEDES JOHN EDWIN');
-- ABRIL: RODRIGUEZ MARCHAN ANGEL DAVID / SUBPRODUCTOS COMESTIBLES -> 12/04/2002
UPDATE empleado SET fecha_nacimiento = '12/04/2002' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('RODRIGUEZ MARCHAN ANGEL DAVID');
-- ABRIL: ANDRADES IBAÑEZ JOSE FRANCISCO / LINEA DE SACRIFICIO -> 15/04/1986
UPDATE empleado SET fecha_nacimiento = '15/04/1986' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('ANDRADES IBAÑEZ JOSE FRANCISCO');
-- ABRIL: SANCHEZ GUTIERREZ JOHNY ALEJANDRO / LINEA DE SACRIFICIO -> 15/04/1995
UPDATE empleado SET fecha_nacimiento = '15/04/1995' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('SANCHEZ GUTIERREZ JOHNY ALEJANDRO');
-- ABRIL: VARGAS BERROTERAN DARWIN ARVEY / LOGISTICA -> 16/04/1999
UPDATE empleado SET fecha_nacimiento = '16/04/1999' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('VARGAS BERROTERAN DARWIN ARVEY');
-- ABRIL: PINEDA TRIANA VIVIANA ANDREA / TESORERIA -> 17/04/1989
UPDATE empleado SET fecha_nacimiento = '17/04/1989' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('PINEDA TRIANA VIVIANA ANDREA');
-- ABRIL: DELGADO RINCON KAREN DANIELA / GESTION HUMANA -> 18/04/2008
UPDATE empleado SET fecha_nacimiento = '18/04/2008' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('DELGADO RINCON KAREN DANIELA');
-- ABRIL: CASTELLANOS OLIVEROS NEIDER IVAN / PTAP -> 19/04/1997
UPDATE empleado SET fecha_nacimiento = '19/04/1997' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('CASTELLANOS OLIVEROS NEIDER IVAN');
-- ABRIL: SANCHEZ GALVIS MARILUZ / LIMPIEZA Y DESINFECCION -> 22/04/1983
UPDATE empleado SET fecha_nacimiento = '22/04/1983' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('SANCHEZ GALVIS MARILUZ');
-- ABRIL: REYES SISA VICTOR ALFONSO / SUBPRODUCTOS COMESTIBLES -> 22/04/1993
UPDATE empleado SET fecha_nacimiento = '22/04/1993' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('REYES SISA VICTOR ALFONSO');
-- ABRIL: VANEGAS SANTANA HERIBERTO / SUBPRODUCTOS COMESTIBLES -> 23/04/1983
UPDATE empleado SET fecha_nacimiento = '23/04/1983' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('VANEGAS SANTANA HERIBERTO');
-- ABRIL: HERNANDEZ CUELLO ANDRES FELIPE / LINEA DE SACRIFICIO -> 26/04/2005
UPDATE empleado SET fecha_nacimiento = '26/04/2005' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('HERNANDEZ CUELLO ANDRES FELIPE');
-- ABRIL: PARADA ORTEGA GUSTAVO ADOLFO / LOGISTICA DESPOSTE -> 28/04/1993
UPDATE empleado SET fecha_nacimiento = '28/04/1993' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('PARADA ORTEGA GUSTAVO ADOLFO');
-- MAYO: GUERRERO GUERRERO JOSE RODRIGO / PTAR -> 02/05/1999
UPDATE empleado SET fecha_nacimiento = '02/05/1999' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('GUERRERO GUERRERO JOSE RODRIGO');
-- MAYO: LOZADA ORTIZ TELMO / LOGISTICA -> 04/05/1987
UPDATE empleado SET fecha_nacimiento = '04/05/1987' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('LOZADA ORTIZ TELMO');
-- MAYO: LEAL MARCHAN JESUS MIGUEL / SUBPRODUCTOS COMESTIBLES -> 05/05/1991
UPDATE empleado SET fecha_nacimiento = '05/05/1991' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('LEAL MARCHAN JESUS MIGUEL');
-- MAYO: RINCON BOTELLO YERSON JAVIER / SUBPRODUCTOS COMESTIBLES -> 05/05/1989
UPDATE empleado SET fecha_nacimiento = '05/05/1989' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('RINCON BOTELLO YERSON JAVIER');
-- MAYO: PARADA SIERRA FABIO ENRIQUE / LINEA DE SACRIFICIO -> 07/05/1996
UPDATE empleado SET fecha_nacimiento = '07/05/1996' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('PARADA SIERRA FABIO ENRIQUE');
-- MAYO: AMADOR SUAN SIXTO / SUBPRODUCTOS COMESTIBLES -> 07/05/1968
UPDATE empleado SET fecha_nacimiento = '07/05/1968' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('AMADOR SUAN SIXTO');
-- MAYO: OSORIO ZANDUA JUAN SEBASTIAN / GESTION HUMANA -> 09/05/1995
UPDATE empleado SET fecha_nacimiento = '09/05/1995' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('OSORIO ZANDUA JUAN SEBASTIAN');
-- MAYO: BETANCURT AGUDELO LUZ JASMIN / SUBPRODUCTOS COMESTIBLES -> 10/05/1977
UPDATE empleado SET fecha_nacimiento = '10/05/1977' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('BETANCURT AGUDELO LUZ JASMIN');
-- MAYO: ARDILA PARRA JOAO CARLOS / LINEA DESPOSTE -> 11/05/1985
UPDATE empleado SET fecha_nacimiento = '11/05/1985' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('ARDILA PARRA JOAO CARLOS');
-- MAYO: CRUZ QUIROGA MAYKIN ALIRIO / LOGISTICA -> 12/05/1984
UPDATE empleado SET fecha_nacimiento = '12/05/1984' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('CRUZ QUIROGA MAYKIN ALIRIO');
-- MAYO: CAMACHO DIAZ DIEGO / LINEA DE SACRIFICIO -> 12/05/1992
UPDATE empleado SET fecha_nacimiento = '12/05/1992' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('CAMACHO DIAZ DIEGO');
-- MAYO: HIGUERA JAIMES ADRIANA LICETH / CALIDAD DESPOSTE -> 14/05/2003
UPDATE empleado SET fecha_nacimiento = '14/05/2003' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('HIGUERA JAIMES ADRIANA LICETH');
-- MAYO: SOLANO GOMEZ VICTOR ALFONSO / LINEA DESPOSTE -> 17/05/1985
UPDATE empleado SET fecha_nacimiento = '17/05/1985' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('SOLANO GOMEZ VICTOR ALFONSO');
-- MAYO: MOGOLLON HERRENO JHON FREDY / LINEA DE SACRIFICIO -> 17/05/1991
UPDATE empleado SET fecha_nacimiento = '17/05/1991' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('MOGOLLON HERRENO JHON FREDY');
-- MAYO: CALA CARVAJAL JAIDER ASDRUVAL / LOGISTICA -> 19/05/2003
UPDATE empleado SET fecha_nacimiento = '19/05/2003' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('CALA CARVAJAL JAIDER ASDRUVAL');
-- MAYO: RENGIFO MORA OSCAR ALEJANDRO / SUBPRODUCTOS COMESTIBLES -> 19/05/1985
UPDATE empleado SET fecha_nacimiento = '19/05/1985' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('RENGIFO MORA OSCAR ALEJANDRO');
-- MAYO: DIAZ VILLAMIZAR JAVIER ESTEVEN / SUBPRODUCTOS COMESTIBLES -> 22/05/2000
UPDATE empleado SET fecha_nacimiento = '22/05/2000' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('DIAZ VILLAMIZAR JAVIER ESTEVEN');
-- MAYO: CARDENAS CARDENAS CARLOS ANDRES / PTAR -> 23/05/2002
UPDATE empleado SET fecha_nacimiento = '23/05/2002' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('CARDENAS CARDENAS CARLOS ANDRES');
-- MAYO: RAMIREZ VARGAS OLINTO / LINEA DE SACRIFICIO -> 23/05/1965
UPDATE empleado SET fecha_nacimiento = '23/05/1965' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('RAMIREZ VARGAS OLINTO');
-- MAYO: BONILLA BELTRAN SERGIO ANDRES / LINEA DE SACRIFICIO -> 26/05/1994
UPDATE empleado SET fecha_nacimiento = '26/05/1994' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('BONILLA BELTRAN SERGIO ANDRES');
-- MAYO: ROMERO URIBE ARNOL BRAN / LINEA DE SACRIFICIO -> 26/05/2005
UPDATE empleado SET fecha_nacimiento = '26/05/2005' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('ROMERO URIBE ARNOL BRAN');
-- MAYO: MOLINA RINCON LUIS MANUEL / LOGISTICA -> 26/05/1986
UPDATE empleado SET fecha_nacimiento = '26/05/1986' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('MOLINA RINCON LUIS MANUEL');
-- MAYO: BUITRAGO MENDEZ ADRIANA ROCIO / DIRECCION DPTO CALIDAD -> 27/05/1999
UPDATE empleado SET fecha_nacimiento = '27/05/1999' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('BUITRAGO MENDEZ ADRIANA ROCIO');
-- MAYO: MANTILLA DELGADO LUIS ERNESTO / LINEA DE SACRIFICIO -> 28/05/1982
UPDATE empleado SET fecha_nacimiento = '28/05/1982' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('MANTILLA DELGADO LUIS ERNESTO');
-- MAYO: LOPEZ HURTADO ANDRES FABIAN / LINEA DE SACRIFICIO -> 29/05/1988
UPDATE empleado SET fecha_nacimiento = '29/05/1988' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('LOPEZ HURTADO ANDRES FABIAN');
-- MAYO: FERNANDEZ LUNA ALEXANDER / RECEPCION Y PESAJE -> 29/05/1977
UPDATE empleado SET fecha_nacimiento = '29/05/1977' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('FERNANDEZ LUNA ALEXANDER');
-- MAYO: VARGAS DURAN ROBINSON / PRODUCCION DESPOSTE -> 31/05/1975
UPDATE empleado SET fecha_nacimiento = '31/05/1975' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('VARGAS DURAN ROBINSON');
-- JUNIO: VILLALBA ORTEGA JOHAN FERNANDO / LINEA DESPOSTE -> 01/06/2000
UPDATE empleado SET fecha_nacimiento = '01/06/2000' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('VILLALBA ORTEGA JOHAN FERNANDO');
-- JUNIO: AGUDELO SAJONERO JHONATAN / LOGISTICA -> 01/06/2000
UPDATE empleado SET fecha_nacimiento = '01/06/2000' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('AGUDELO SAJONERO JHONATAN');
-- JUNIO: ANGARITA CASTILLO HERSON DAVID / PORCIONADO -> 02/06/1986
UPDATE empleado SET fecha_nacimiento = '02/06/1986' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('ANGARITA CASTILLO HERSON DAVID');
-- JUNIO: BOTHIA CARDENAS OMAR STEBEN / LOGISTICA -> 04/06/2003
UPDATE empleado SET fecha_nacimiento = '04/06/2003' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('BOTHIA CARDENAS OMAR STEBEN');
-- JUNIO: HOYOS NIÑO ANDRES FELIPE / LINEA DE SACRIFICIO -> 05/06/2001
UPDATE empleado SET fecha_nacimiento = '05/06/2001' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('HOYOS NIÑO ANDRES FELIPE');
-- JUNIO: SERRANO ARDILA DIEGO FERNANDO / DIRECCION ADMON Y FINANCIERA -> 06/06/1978
UPDATE empleado SET fecha_nacimiento = '06/06/1978' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('SERRANO ARDILA DIEGO FERNANDO');
-- JUNIO: PEÑA PEÑA LUIS DAVID / SUBPRODUCTOS COMESTIBLES -> 06/06/1998
UPDATE empleado SET fecha_nacimiento = '06/06/1998' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('PEÑA PEÑA LUIS DAVID');
-- JUNIO: GUERRERO RAMOS LUIS DAVID / SUBPRODUCTOS COMESTIBLES -> 07/06/1995
UPDATE empleado SET fecha_nacimiento = '07/06/1995' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('GUERRERO RAMOS LUIS DAVID');
-- JUNIO: ROJAS GUTIERREZ JHON FREDY / SUBPRODUCTOS COMESTIBLES -> 08/06/1993
UPDATE empleado SET fecha_nacimiento = '08/06/1993' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('ROJAS GUTIERREZ JHON FREDY');
-- JUNIO: BOTHIA RAMIREZ OMAR / SUBPRODUCTOS COMESTIBLES -> 08/06/1978
UPDATE empleado SET fecha_nacimiento = '08/06/1978' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('BOTHIA RAMIREZ OMAR');
-- JUNIO: RUEDA MADERO PAOLA CAROLINA / DIRECCION DPTO COMERCIAL -> 11/06/1988
UPDATE empleado SET fecha_nacimiento = '11/06/1988' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('RUEDA MADERO PAOLA CAROLINA');
-- JUNIO: CORTES NIÑO YENSON ERNESTO / LINEA DE SACRIFICIO -> 12/06/1977
UPDATE empleado SET fecha_nacimiento = '12/06/1977' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('CORTES NIÑO YENSON ERNESTO');
-- JUNIO: CALDERON LOPEZ CAROL YULIANA / INVIMA -> 13/06/2002
UPDATE empleado SET fecha_nacimiento = '13/06/2002' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('CALDERON LOPEZ CAROL YULIANA');
-- JUNIO: BARRIOS RUIZ MIGUEL ANGEL / LOGISTICA -> 13/06/1993
UPDATE empleado SET fecha_nacimiento = '13/06/1993' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('BARRIOS RUIZ MIGUEL ANGEL');
-- JUNIO: BOLAÑO ALVAREZ HERNAN JOSE / LINEA DE SACRIFICIO -> 17/06/1995
UPDATE empleado SET fecha_nacimiento = '17/06/1995' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('BOLAÑO ALVAREZ HERNAN JOSE');
-- JUNIO: BOHORQUEZ ANGARITA ANDRES FELIPE / L&D DESPOSTE -> 22/06/1999
UPDATE empleado SET fecha_nacimiento = '22/06/1999' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('BOHORQUEZ ANGARITA ANDRES FELIPE');
-- JUNIO: JAIMES JAIMES FEDERICO / LINEA DE SACRIFICIO -> 21/06/1969
UPDATE empleado SET fecha_nacimiento = '21/06/1969' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('JAIMES JAIMES FEDERICO');
-- JUNIO: BAUTISTA CRUZ JOSE DANIEL / LIMPIEZA Y DESINFECCION -> 23/06/1997
UPDATE empleado SET fecha_nacimiento = '23/06/1997' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('BAUTISTA CRUZ JOSE DANIEL');
-- JUNIO: ROJAS BARRERA CAMILO ANDRES / MERCADEO -> 24/06/1988
UPDATE empleado SET fecha_nacimiento = '24/06/1988' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('ROJAS BARRERA CAMILO ANDRES');
-- JUNIO: ANAYA LANDAZABAL SERGIO ANDRES / LOGISTICA -> 24/06/1985
UPDATE empleado SET fecha_nacimiento = '24/06/1985' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('ANAYA LANDAZABAL SERGIO ANDRES');
-- JUNIO: BECERRA JAIMES DIEGO ARMANDO / LINEA DE SACRIFICIO -> 27/06/1992
UPDATE empleado SET fecha_nacimiento = '27/06/1992' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('BECERRA JAIMES DIEGO ARMANDO');
-- JUNIO: VILLAMIZAR RODRIGUEZ IVAN / SUBPRODUCTOS COMESTIBLES -> 27/06/1988
UPDATE empleado SET fecha_nacimiento = '27/06/1988' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('VILLAMIZAR RODRIGUEZ IVAN');
-- JUNIO: CONDE VILLAMIZAR YENNIFER ROCIO / TESORERIA -> 28/06/2001
UPDATE empleado SET fecha_nacimiento = '28/06/2001' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('CONDE VILLAMIZAR YENNIFER ROCIO');
-- JUNIO: LOPEZ ARIZA PEDRO ANTONIO / RECEPCION Y PESAJE -> 29/06/1983
UPDATE empleado SET fecha_nacimiento = '29/06/1983' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('LOPEZ ARIZA PEDRO ANTONIO');
-- JUNIO: RINCON DIAZ MILTON YESID / LOGISTICA -> 10/06/2000
UPDATE empleado SET fecha_nacimiento = '10/06/2000' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('RINCON DIAZ MILTON YESID');
-- JUNIO: ANTON RODRIGUEZ HECTOR LUIS / SUBPRODUCTOS COMESTIBLES -> 16/06/1984
UPDATE empleado SET fecha_nacimiento = '16/06/1984' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('ANTON RODRIGUEZ HECTOR LUIS');
-- JUNIO: ROJAS HERNANDEZ JUAN CARLOS / LINEA DE SACRIFICIO -> 04/06/1991
UPDATE empleado SET fecha_nacimiento = '04/06/1991' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('ROJAS HERNANDEZ JUAN CARLOS');
-- JUNIO: RUEDA PARRA EDWIN ORLANDO / SUBPRODUCTOS COMESTIBLES -> 22/06/1989
UPDATE empleado SET fecha_nacimiento = '22/06/1989' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('RUEDA PARRA EDWIN ORLANDO');
-- JUNIO: SOTELO TORCEDILLA ROBINSON / RECEPCION Y PESAJE -> 23/06/1982
UPDATE empleado SET fecha_nacimiento = '23/06/1982' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('SOTELO TORCEDILLA ROBINSON');

COMMIT;
