-- SQL limpio de cumpleaños generado desde la fuente CUMPLEAÑOS 2026
-- Corrige fechas ambiguas copiando la fecha real de la fuente, no por heurística.
USE gestio_humana;
START TRANSACTION;

-- ENERO: AYALA PEÑARANDA CRISTIAN DAVID / LINEA DE SACRIFICIO -> 02/01/2003
UPDATE empleado SET fecha_nacimiento = '02/01/2003' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('AYALA PEÑARANDA CRISTIAN DAVID') AND UPPER(TRIM(area)) = UPPER('LINEA DE SACRIFICIO');
-- ENERO: RODRIGUEZ RUIZ ALEXANDER / PLANEACION -> 02/01/1989
UPDATE empleado SET fecha_nacimiento = '02/01/1989' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('RODRIGUEZ RUIZ ALEXANDER') AND UPPER(TRIM(area)) = UPPER('PLANEACION');
-- ENERO: PABON SERRANO ANDERSON / LINEA DE SACRIFICIO -> 03/01/2002
UPDATE empleado SET fecha_nacimiento = '03/01/2002' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('PABON SERRANO ANDERSON') AND UPPER(TRIM(area)) = UPPER('LINEA DE SACRIFICIO');
-- ENERO: SANTOS TORRA CARLOS ALBERTO / LINEA DESPOSTE -> 04/01/1984
UPDATE empleado SET fecha_nacimiento = '04/01/1984' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('SANTOS TORRA CARLOS ALBERTO') AND UPPER(TRIM(area)) = UPPER('LINEA DESPOSTE');
-- ENERO: SANCHEZ URIBE EDIVAN / LOGISTICA -> 04/01/2000
UPDATE empleado SET fecha_nacimiento = '04/01/2000' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('SANCHEZ URIBE EDIVAN') AND UPPER(TRIM(area)) = UPPER('LOGISTICA');
-- ENERO: PIÑERES ROCHA CHRISTIAN CAMILO / LINEA DESPOSTE -> 05/01/1999
UPDATE empleado SET fecha_nacimiento = '05/01/1999' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('PIÑERES ROCHA CHRISTIAN CAMILO') AND UPPER(TRIM(area)) = UPPER('LINEA DESPOSTE');
-- ENERO: GALEANO ROA DANIEL ESTIVEN / DIRECCION DPTO CALIDAD -> 05/01/2003
UPDATE empleado SET fecha_nacimiento = '05/01/2003' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('GALEANO ROA DANIEL ESTIVEN') AND UPPER(TRIM(area)) = UPPER('DIRECCION DPTO CALIDAD');
-- ENERO: CASTILLO MARIN JOSE LUIS / SUBPRODUCTOS COMESTIBLES -> 05/01/1999
UPDATE empleado SET fecha_nacimiento = '05/01/1999' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('CASTILLO MARIN JOSE LUIS') AND UPPER(TRIM(area)) = UPPER('SUBPRODUCTOS COMESTIBLES');
-- ENERO: AGUDELO CORTES OSCAR MAURICIO / LOGISTICA DESPOSTE -> 07/01/2003
UPDATE empleado SET fecha_nacimiento = '07/01/2003' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('AGUDELO CORTES OSCAR MAURICIO') AND UPPER(TRIM(area)) = UPPER('LOGISTICA DESPOSTE');
-- ENERO: SANCHEZ RODRIGUEZ EUDY JOSE / LOGISTICA -> 07/01/1996
UPDATE empleado SET fecha_nacimiento = '07/01/1996' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('SANCHEZ RODRIGUEZ EUDY JOSE') AND UPPER(TRIM(area)) = UPPER('LOGISTICA');
-- ENERO: GONZALEZ DELGADO EDUAR VIRLEY / LINEA DESPOSTE -> 12/01/1985
UPDATE empleado SET fecha_nacimiento = '12/01/1985' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('GONZALEZ DELGADO EDUAR VIRLEY') AND UPPER(TRIM(area)) = UPPER('LINEA DESPOSTE');
-- ENERO: CARDENAS CAICEDO URIEL / LINEA DE SACRIFICIO -> 13/01/1981
UPDATE empleado SET fecha_nacimiento = '13/01/1981' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('CARDENAS CAICEDO URIEL') AND UPPER(TRIM(area)) = UPPER('LINEA DE SACRIFICIO');
-- ENERO: OLIVERA FLOREZ JOSE GABRIEL / SUBPRODUCTOS COMESTIBLES -> 14/01/1985
UPDATE empleado SET fecha_nacimiento = '14/01/1985' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('OLIVERA FLOREZ JOSE GABRIEL') AND UPPER(TRIM(area)) = UPPER('SUBPRODUCTOS COMESTIBLES');
-- ENERO: CARREÑO MENDOZA JUAN PABLO / TECNOLOGIA -> 15/01/2000
UPDATE empleado SET fecha_nacimiento = '15/01/2000' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('CARREÑO MENDOZA JUAN PABLO') AND UPPER(TRIM(area)) = UPPER('TECNOLOGIA');
-- ENERO: RINCON MENDOZA DUBIAN ERNEY / LIMPIEZA Y DESINFECCION -> 17/01/1997
UPDATE empleado SET fecha_nacimiento = '17/01/1997' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('RINCON MENDOZA DUBIAN ERNEY') AND UPPER(TRIM(area)) = UPPER('LIMPIEZA Y DESINFECCION');
-- ENERO: LOZADA ORTIZ OLIVER SEBASTIAN / LOGISTICA DESPOSTE -> 20/01/1994
UPDATE empleado SET fecha_nacimiento = '20/01/1994' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('LOZADA ORTIZ OLIVER SEBASTIAN') AND UPPER(TRIM(area)) = UPPER('LOGISTICA DESPOSTE');
-- ENERO: COTE HERNANDEZ MARIA CAMILA / INVIMA -> 21/01/2000
UPDATE empleado SET fecha_nacimiento = '21/01/2000' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('COTE HERNANDEZ MARIA CAMILA') AND UPPER(TRIM(area)) = UPPER('INVIMA');
-- ENERO: RUEDA TARAZONA JUAN MANUEL / RECEPCION Y PESAJE -> 24/01/2003
UPDATE empleado SET fecha_nacimiento = '24/01/2003' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('RUEDA TARAZONA JUAN MANUEL') AND UPPER(TRIM(area)) = UPPER('RECEPCION Y PESAJE');
-- ENERO: AGON PEDRAZA JAIRO FABIAN / SUBPRODUCTOS COMESTIBLES -> 26/01/2001
UPDATE empleado SET fecha_nacimiento = '26/01/2001' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('AGON PEDRAZA JAIRO FABIAN') AND UPPER(TRIM(area)) = UPPER('SUBPRODUCTOS COMESTIBLES');
-- ENERO: PACHECO MANRIQUE ANDRES FELIPE / LINEA DE SACRIFICIO -> 26/01/1998
UPDATE empleado SET fecha_nacimiento = '26/01/1998' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('PACHECO MANRIQUE ANDRES FELIPE') AND UPPER(TRIM(area)) = UPPER('LINEA DE SACRIFICIO');
-- ENERO: MOGOLLON TOLOZA JESUS DAVID / LIMPIEZA Y DESINFECCION -> 27/01/1998
UPDATE empleado SET fecha_nacimiento = '27/01/1998' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('MOGOLLON TOLOZA JESUS DAVID') AND UPPER(TRIM(area)) = UPPER('LIMPIEZA Y DESINFECCION');
-- ENERO: GOMEZ MARTINEZ NIDIA ROCIO / DIRECCION DPTO JURIDICO Y GESTION HUMANA -> 28/01/1980
UPDATE empleado SET fecha_nacimiento = '28/01/1980' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('GOMEZ MARTINEZ NIDIA ROCIO') AND UPPER(TRIM(area)) = UPPER('DIRECCION DPTO JURIDICO Y GESTION HUMANA');
-- ENERO: GARCIA LINARES FREILEN BRANYAN / LOGISTICA -> 29/01/1993
UPDATE empleado SET fecha_nacimiento = '29/01/1993' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('GARCIA LINARES FREILEN BRANYAN') AND UPPER(TRIM(area)) = UPPER('LOGISTICA');
-- ENERO: ROCHA FUENTES JUAN DAVID / LOGISTICA DESPOSTE -> 31/01/2002
UPDATE empleado SET fecha_nacimiento = '31/01/2002' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('ROCHA FUENTES JUAN DAVID') AND UPPER(TRIM(area)) = UPPER('LOGISTICA DESPOSTE');
-- FEBRERO: SILVERA FLORES LUIGY OBRAYAN / SUBPRODUCTOS COMESTIBLES -> 01/02/2002
UPDATE empleado SET fecha_nacimiento = '01/02/2002' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('SILVERA FLORES LUIGY OBRAYAN') AND UPPER(TRIM(area)) = UPPER('SUBPRODUCTOS COMESTIBLES');
-- FEBRERO: RONCALLO RADA JOSE LUIS / LINEA DE SACRIFICIO -> 01/02/1995
UPDATE empleado SET fecha_nacimiento = '01/02/1995' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('RONCALLO RADA JOSE LUIS') AND UPPER(TRIM(area)) = UPPER('LINEA DE SACRIFICIO');
-- FEBRERO: GARCIA ANDRADES VICTOR ALFONSO / RECEPCION Y PESAJE -> 02/02/1993
UPDATE empleado SET fecha_nacimiento = '02/02/1993' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('GARCIA ANDRADES VICTOR ALFONSO') AND UPPER(TRIM(area)) = UPPER('RECEPCION Y PESAJE');
-- FEBRERO: LOBO VELASQUEZ LUIS HERNANDO / LIMPIEZA Y DESINFECCION -> 03/02/2000
UPDATE empleado SET fecha_nacimiento = '03/02/2000' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('LOBO VELASQUEZ LUIS HERNANDO') AND UPPER(TRIM(area)) = UPPER('LIMPIEZA Y DESINFECCION');
-- FEBRERO: ARIAS PARADA JHONATAN DAVID / DIRECCION DPTO CALIDAD -> 04/02/2001
UPDATE empleado SET fecha_nacimiento = '04/02/2001' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('ARIAS PARADA JHONATAN DAVID') AND UPPER(TRIM(area)) = UPPER('DIRECCION DPTO CALIDAD');
-- FEBRERO: SOTO MATEUS WILMAR / RECEPCION Y PESAJE -> 04/02/1980
UPDATE empleado SET fecha_nacimiento = '04/02/1980' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('SOTO MATEUS WILMAR') AND UPPER(TRIM(area)) = UPPER('RECEPCION Y PESAJE');
-- FEBRERO: HERNANDEZ DURAN PEDRO JOSE / LIMPIEZA Y DESINFECCION -> 05/02/1995
UPDATE empleado SET fecha_nacimiento = '05/02/1995' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('HERNANDEZ DURAN PEDRO JOSE') AND UPPER(TRIM(area)) = UPPER('LIMPIEZA Y DESINFECCION');
-- FEBRERO: CAMACHO ARENAS EMERSON ALBERTO / SUBPRODUCTOS COMESTIBLES -> 05/02/2000
UPDATE empleado SET fecha_nacimiento = '05/02/2000' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('CAMACHO ARENAS EMERSON ALBERTO') AND UPPER(TRIM(area)) = UPPER('SUBPRODUCTOS COMESTIBLES');
-- FEBRERO: RIVERA COLMENARES JHON NEIDER / SUBPRODUCTOS COMESTIBLES -> 05/02/1993
UPDATE empleado SET fecha_nacimiento = '05/02/1993' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('RIVERA COLMENARES JHON NEIDER') AND UPPER(TRIM(area)) = UPPER('SUBPRODUCTOS COMESTIBLES');
-- FEBRERO: RUBIANO LEMUS YUDY ANDREA / DIRECCION DPTO CALIDAD -> 07/02/1985
UPDATE empleado SET fecha_nacimiento = '07/02/1985' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('RUBIANO LEMUS YUDY ANDREA') AND UPPER(TRIM(area)) = UPPER('DIRECCION DPTO CALIDAD');
-- FEBRERO: JAIMES DIAZ ALEXANDER / SUBPRODUCTOS COMESTIBLES -> 09/02/1982
UPDATE empleado SET fecha_nacimiento = '09/02/1982' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('JAIMES DIAZ ALEXANDER') AND UPPER(TRIM(area)) = UPPER('SUBPRODUCTOS COMESTIBLES');
-- FEBRERO: MANTILLA SAAVEDRA YEVINSON RENE / LINEA DE SACRIFICIO -> 10/02/2007
UPDATE empleado SET fecha_nacimiento = '10/02/2007' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('MANTILLA SAAVEDRA YEVINSON RENE') AND UPPER(TRIM(area)) = UPPER('LINEA DE SACRIFICIO');
-- FEBRERO: MEDINA CARLOS SNEYDER / CONTABILIDAD -> 10/02/1990
UPDATE empleado SET fecha_nacimiento = '10/02/1990' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('MEDINA CARLOS SNEYDER') AND UPPER(TRIM(area)) = UPPER('CONTABILIDAD');
-- FEBRERO: ALVAREZ ARVELO ROKY DAVID / TESORERIA -> 10/02/1987
UPDATE empleado SET fecha_nacimiento = '10/02/1987' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('ALVAREZ ARVELO ROKY DAVID') AND UPPER(TRIM(area)) = UPPER('TESORERIA');
-- FEBRERO: PONTON PONTON EVER MAURICIO / LINEA DE SACRIFICIO -> 10/02/1997
UPDATE empleado SET fecha_nacimiento = '10/02/1997' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('PONTON PONTON EVER MAURICIO') AND UPPER(TRIM(area)) = UPPER('LINEA DE SACRIFICIO');
-- FEBRERO: SAAVEDRA SANTISTEBAN LAURA MELISSA / COMPRAS -> 11/02/1987
UPDATE empleado SET fecha_nacimiento = '11/02/1987' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('SAAVEDRA SANTISTEBAN LAURA MELISSA') AND UPPER(TRIM(area)) = UPPER('COMPRAS');
-- FEBRERO: GONZALEZ MIELES ADALGIZA / CONTABILIDAD -> 12/02/1992
UPDATE empleado SET fecha_nacimiento = '12/02/1992' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('GONZALEZ MIELES ADALGIZA') AND UPPER(TRIM(area)) = UPPER('CONTABILIDAD');
-- FEBRERO: SANTERO SUAREZ EVELIO ISAAC / LOGISTICA -> 14/02/1999
UPDATE empleado SET fecha_nacimiento = '14/02/1999' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('SANTERO SUAREZ EVELIO ISAAC') AND UPPER(TRIM(area)) = UPPER('LOGISTICA');
-- FEBRERO: SILVA QUIJANO ANDERSON JULIAN / SUBPRODUCTOS COMESTIBLES -> 14/02/2000
UPDATE empleado SET fecha_nacimiento = '14/02/2000' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('SILVA QUIJANO ANDERSON JULIAN') AND UPPER(TRIM(area)) = UPPER('SUBPRODUCTOS COMESTIBLES');
-- FEBRERO: SUAREZ JAIMES ALBERTO / LINEA DE SACRIFICIO -> 15/02/1985
UPDATE empleado SET fecha_nacimiento = '15/02/1985' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('SUAREZ JAIMES ALBERTO') AND UPPER(TRIM(area)) = UPPER('LINEA DE SACRIFICIO');
-- FEBRERO: TOLOZA JAIMES CLEIVER ERMIDES / LINEA DE SACRIFICIO -> 15/02/1991
UPDATE empleado SET fecha_nacimiento = '15/02/1991' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('TOLOZA JAIMES CLEIVER ERMIDES') AND UPPER(TRIM(area)) = UPPER('LINEA DE SACRIFICIO');
-- FEBRERO: RINCON TORRES JAVIER ENRIQUE / SUBPRODUCTOS COMESTIBLES -> 16/02/1984
UPDATE empleado SET fecha_nacimiento = '16/02/1984' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('RINCON TORRES JAVIER ENRIQUE') AND UPPER(TRIM(area)) = UPPER('SUBPRODUCTOS COMESTIBLES');
-- FEBRERO: PEÑA ARENAS PEDRO ARMANDO / L&D DESPOSTE -> 16/02/2001
UPDATE empleado SET fecha_nacimiento = '16/02/2001' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('PEÑA ARENAS PEDRO ARMANDO') AND UPPER(TRIM(area)) = UPPER('L&D DESPOSTE');
-- FEBRERO: AMAYA TASCO JORGE ALEXIS / LINEA DESPOSTE -> 18/02/1989
UPDATE empleado SET fecha_nacimiento = '18/02/1989' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('AMAYA TASCO JORGE ALEXIS') AND UPPER(TRIM(area)) = UPPER('LINEA DESPOSTE');
-- FEBRERO: GUALDRON CASTELLANOS NELSON ENRIQUE / LOGISTICA -> 21/02/1985
UPDATE empleado SET fecha_nacimiento = '21/02/1985' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('GUALDRON CASTELLANOS NELSON ENRIQUE') AND UPPER(TRIM(area)) = UPPER('LOGISTICA');
-- FEBRERO: HERNANDEZ URZOLA ROBERTO CARLOS / DIRECCION DPTO COMERCIAL -> 22/02/1972
UPDATE empleado SET fecha_nacimiento = '22/02/1972' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('HERNANDEZ URZOLA ROBERTO CARLOS') AND UPPER(TRIM(area)) = UPPER('DIRECCION DPTO COMERCIAL');
-- FEBRERO: MARQUEZ RODRIGUEZ SILVIA JULIANA / GESTION HUMANA -> 23/02/1995
UPDATE empleado SET fecha_nacimiento = '23/02/1995' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('MARQUEZ RODRIGUEZ SILVIA JULIANA') AND UPPER(TRIM(area)) = UPPER('GESTION HUMANA');
-- FEBRERO: SEGURA BARRERA MARIA FILOMENA / DIRECCION DPTO CALIDAD -> 23/02/1987
UPDATE empleado SET fecha_nacimiento = '23/02/1987' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('SEGURA BARRERA MARIA FILOMENA') AND UPPER(TRIM(area)) = UPPER('DIRECCION DPTO CALIDAD');
-- FEBRERO: CORREA MANRIQUE LEONARDO / LIMPIEZA Y DESINFECCION -> 26/02/1990
UPDATE empleado SET fecha_nacimiento = '26/02/1990' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('CORREA MANRIQUE LEONARDO') AND UPPER(TRIM(area)) = UPPER('LIMPIEZA Y DESINFECCION');
-- FEBRERO: RODRIGUEZ HERNANDEZ ANDRES MAURICIO / LOGISTICA -> 27/02/1992
UPDATE empleado SET fecha_nacimiento = '27/02/1992' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('RODRIGUEZ HERNANDEZ ANDRES MAURICIO') AND UPPER(TRIM(area)) = UPPER('LOGISTICA');
-- FEBRERO: RIVERA GOMEZ CAMILO ANDRES / SUBPRODUCTOS COMESTIBLES -> 28/02/2003
UPDATE empleado SET fecha_nacimiento = '28/02/2003' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('RIVERA GOMEZ CAMILO ANDRES') AND UPPER(TRIM(area)) = UPPER('SUBPRODUCTOS COMESTIBLES');
-- MARZO: MORENO MARTINEZ JESUS ANTONIO / SUBPRODUCTOS COMESTIBLES -> 01/03/1988
UPDATE empleado SET fecha_nacimiento = '01/03/1988' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('MORENO MARTINEZ JESUS ANTONIO') AND UPPER(TRIM(area)) = UPPER('SUBPRODUCTOS COMESTIBLES');
-- MARZO: SANABRIA TORRES YEBERSON LEANDRO / LINEA DE SACRIFICIO -> 01/03/1996
UPDATE empleado SET fecha_nacimiento = '01/03/1996' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('SANABRIA TORRES YEBERSON LEANDRO') AND UPPER(TRIM(area)) = UPPER('LINEA DE SACRIFICIO');
-- MARZO: MIRANDA HERNANDEZ KAREN JOHANNA / CALIDAD DESPOSTE -> 04/03/2000
UPDATE empleado SET fecha_nacimiento = '04/03/2000' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('MIRANDA HERNANDEZ KAREN JOHANNA') AND UPPER(TRIM(area)) = UPPER('CALIDAD DESPOSTE');
-- MARZO: DELGADO FLOREZ GABRIEL / LINEA DE SACRIFICIO -> 05/03/1985
UPDATE empleado SET fecha_nacimiento = '05/03/1985' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('DELGADO FLOREZ GABRIEL') AND UPPER(TRIM(area)) = UPPER('LINEA DE SACRIFICIO');
-- MARZO: MEJIA GUERRERO FRANCISCO / PTAR -> 07/03/1966
UPDATE empleado SET fecha_nacimiento = '07/03/1966' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('MEJIA GUERRERO FRANCISCO') AND UPPER(TRIM(area)) = UPPER('PTAR');
-- MARZO: CARRILLO GONZALEZ SARAI DANIELA / TESORERIA -> 08/03/2002
UPDATE empleado SET fecha_nacimiento = '08/03/2002' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('CARRILLO GONZALEZ SARAI DANIELA') AND UPPER(TRIM(area)) = UPPER('TESORERIA');
-- MARZO: MANZANO LIZARAZO MANZUR NAIN / L&D DESPOSTE -> 10/03/1992
UPDATE empleado SET fecha_nacimiento = '10/03/1992' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('MANZANO LIZARAZO MANZUR NAIN') AND UPPER(TRIM(area)) = UPPER('L&D DESPOSTE');
-- MARZO: DURAN PUENTES LAUDID / CONTABILIDAD -> 11/03/2002
UPDATE empleado SET fecha_nacimiento = '11/03/2002' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('DURAN PUENTES LAUDID') AND UPPER(TRIM(area)) = UPPER('CONTABILIDAD');
-- MARZO: MORENO GAMA JUAN CARLOS / RECEPCION Y PESAJE -> 15/03/1987
UPDATE empleado SET fecha_nacimiento = '15/03/1987' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('MORENO GAMA JUAN CARLOS') AND UPPER(TRIM(area)) = UPPER('RECEPCION Y PESAJE');
-- MARZO: LOPEZ PEREZ BRAYAN ENRIQUE / DIRECCION DPTO CALIDAD -> 17/03/1996
UPDATE empleado SET fecha_nacimiento = '17/03/1996' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('LOPEZ PEREZ BRAYAN ENRIQUE') AND UPPER(TRIM(area)) = UPPER('DIRECCION DPTO CALIDAD');
-- MARZO: ESPITIA LANDAZABAL JAHIR FABIAN / SUBPRODUCTOS COMESTIBLES -> 20/03/1996
UPDATE empleado SET fecha_nacimiento = '20/03/1996' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('ESPITIA LANDAZABAL JAHIR FABIAN') AND UPPER(TRIM(area)) = UPPER('SUBPRODUCTOS COMESTIBLES');
-- MARZO: AFANADOR PINEDA NELSON / LINEA DE SACRIFICIO -> 22/03/1992
UPDATE empleado SET fecha_nacimiento = '22/03/1992' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('AFANADOR PINEDA NELSON') AND UPPER(TRIM(area)) = UPPER('LINEA DE SACRIFICIO');
-- MARZO: VARGAS OSSES JHON ELKIN / LOGISTICA -> 25/03/1990
UPDATE empleado SET fecha_nacimiento = '25/03/1990' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('VARGAS OSSES JHON ELKIN') AND UPPER(TRIM(area)) = UPPER('LOGISTICA');
-- MARZO: ROMERO PEDRAZA SERGIO OMAR / LINEA DE SACRIFICIO -> 25/03/1993
UPDATE empleado SET fecha_nacimiento = '25/03/1993' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('ROMERO PEDRAZA SERGIO OMAR') AND UPPER(TRIM(area)) = UPPER('LINEA DE SACRIFICIO');
-- MARZO: LOPEZ DELGADO ELICEO / PTAP -> 26/03/1985
UPDATE empleado SET fecha_nacimiento = '26/03/1985' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('LOPEZ DELGADO ELICEO') AND UPPER(TRIM(area)) = UPPER('PTAP');
-- MARZO: ROBLES BELEÑO RONALDO / LINEA DE SACRIFICIO -> 27/03/1998
UPDATE empleado SET fecha_nacimiento = '27/03/1998' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('ROBLES BELEÑO RONALDO') AND UPPER(TRIM(area)) = UPPER('LINEA DE SACRIFICIO');
-- MARZO: MARQUEZ ZERPA YAMPIER JESUS / SUBPRODUCTOS COMESTIBLES -> 30/03/1997
UPDATE empleado SET fecha_nacimiento = '30/03/1997' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('MARQUEZ ZERPA YAMPIER JESUS') AND UPPER(TRIM(area)) = UPPER('SUBPRODUCTOS COMESTIBLES');
-- MARZO: AGUILAR SAAVEDRA LUIS DAVID / LINEA DE SACRIFICIO -> 31/03/2004
UPDATE empleado SET fecha_nacimiento = '31/03/2004' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('AGUILAR SAAVEDRA LUIS DAVID') AND UPPER(TRIM(area)) = UPPER('LINEA DE SACRIFICIO');
-- ABRIL: PARADA SILVA ANDREY ALIRIO / LIMPIEZA Y DESINFECCION -> 05/04/1996
UPDATE empleado SET fecha_nacimiento = '05/04/1996' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('PARADA SILVA ANDREY ALIRIO') AND UPPER(TRIM(area)) = UPPER('LIMPIEZA Y DESINFECCION');
-- ABRIL: BRAVO MARTINEZ DUBAN DAVID / LINEA DE SACRIFICIO -> 05/04/1998
UPDATE empleado SET fecha_nacimiento = '05/04/1998' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('BRAVO MARTINEZ DUBAN DAVID') AND UPPER(TRIM(area)) = UPPER('LINEA DE SACRIFICIO');
-- ABRIL: FERNANDEZ SOLANO ELIO ANTONIO / SUBPRODUCTOS COMESTIBLES -> 07/04/1988
UPDATE empleado SET fecha_nacimiento = '07/04/1988' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('FERNANDEZ SOLANO ELIO ANTONIO') AND UPPER(TRIM(area)) = UPPER('SUBPRODUCTOS COMESTIBLES');
-- ABRIL: AYALA GUTIERREZ JOHN JAIRO / COMPRAS -> 07/04/1987
UPDATE empleado SET fecha_nacimiento = '07/04/1987' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('AYALA GUTIERREZ JOHN JAIRO') AND UPPER(TRIM(area)) = UPPER('COMPRAS');
-- ABRIL: MENDEZ SERRANO ZAIRA YOLIMA / COMPRAS -> 08/04/1980
UPDATE empleado SET fecha_nacimiento = '08/04/1980' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('MENDEZ SERRANO ZAIRA YOLIMA') AND UPPER(TRIM(area)) = UPPER('COMPRAS');
-- ABRIL: BLANCO CAVIEDES JOHN EDWIN / LIMPIEZA Y DESINFECCION -> 11/04/1986
UPDATE empleado SET fecha_nacimiento = '11/04/1986' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('BLANCO CAVIEDES JOHN EDWIN') AND UPPER(TRIM(area)) = UPPER('LIMPIEZA Y DESINFECCION');
-- ABRIL: RODRIGUEZ MARCHAN ANGEL DAVID / SUBPRODUCTOS COMESTIBLES -> 12/04/2002
UPDATE empleado SET fecha_nacimiento = '12/04/2002' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('RODRIGUEZ MARCHAN ANGEL DAVID') AND UPPER(TRIM(area)) = UPPER('SUBPRODUCTOS COMESTIBLES');
-- ABRIL: ANDRADES IBAÑEZ JOSE FRANCISCO / LINEA DE SACRIFICIO -> 15/04/1986
UPDATE empleado SET fecha_nacimiento = '15/04/1986' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('ANDRADES IBAÑEZ JOSE FRANCISCO') AND UPPER(TRIM(area)) = UPPER('LINEA DE SACRIFICIO');
-- ABRIL: SANCHEZ GUTIERREZ JOHNY ALEJANDRO / LINEA DE SACRIFICIO -> 15/04/1995
UPDATE empleado SET fecha_nacimiento = '15/04/1995' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('SANCHEZ GUTIERREZ JOHNY ALEJANDRO') AND UPPER(TRIM(area)) = UPPER('LINEA DE SACRIFICIO');
-- ABRIL: VARGAS BERROTERAN DARWIN ARVEY / LOGISTICA -> 16/04/1999
UPDATE empleado SET fecha_nacimiento = '16/04/1999' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('VARGAS BERROTERAN DARWIN ARVEY') AND UPPER(TRIM(area)) = UPPER('LOGISTICA');
-- ABRIL: PINEDA TRIANA VIVIANA ANDREA / TESORERIA -> 17/04/1989
UPDATE empleado SET fecha_nacimiento = '17/04/1989' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('PINEDA TRIANA VIVIANA ANDREA') AND UPPER(TRIM(area)) = UPPER('TESORERIA');
-- ABRIL: DELGADO RINCON KAREN DANIELA / GESTION HUMANA -> 18/04/2008
UPDATE empleado SET fecha_nacimiento = '18/04/2008' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('DELGADO RINCON KAREN DANIELA') AND UPPER(TRIM(area)) = UPPER('GESTION HUMANA');
-- ABRIL: CASTELLANOS OLIVEROS NEIDER IVAN / PTAP -> 19/04/1997
UPDATE empleado SET fecha_nacimiento = '19/04/1997' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('CASTELLANOS OLIVEROS NEIDER IVAN') AND UPPER(TRIM(area)) = UPPER('PTAP');
-- ABRIL: SANCHEZ GALVIS MARILUZ / LIMPIEZA Y DESINFECCION -> 22/04/1983
UPDATE empleado SET fecha_nacimiento = '22/04/1983' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('SANCHEZ GALVIS MARILUZ') AND UPPER(TRIM(area)) = UPPER('LIMPIEZA Y DESINFECCION');
-- ABRIL: REYES SISA VICTOR ALFONSO / SUBPRODUCTOS COMESTIBLES -> 22/04/1993
UPDATE empleado SET fecha_nacimiento = '22/04/1993' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('REYES SISA VICTOR ALFONSO') AND UPPER(TRIM(area)) = UPPER('SUBPRODUCTOS COMESTIBLES');
-- ABRIL: VANEGAS SANTANA HERIBERTO / SUBPRODUCTOS COMESTIBLES -> 23/04/1983
UPDATE empleado SET fecha_nacimiento = '23/04/1983' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('VANEGAS SANTANA HERIBERTO') AND UPPER(TRIM(area)) = UPPER('SUBPRODUCTOS COMESTIBLES');
-- ABRIL: HERNANDEZ CUELLO ANDRES FELIPE / LINEA DE SACRIFICIO -> 26/04/2005
UPDATE empleado SET fecha_nacimiento = '26/04/2005' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('HERNANDEZ CUELLO ANDRES FELIPE') AND UPPER(TRIM(area)) = UPPER('LINEA DE SACRIFICIO');
-- ABRIL: PARADA ORTEGA GUSTAVO ADOLFO / LOGISTICA DESPOSTE -> 28/04/1993
UPDATE empleado SET fecha_nacimiento = '28/04/1993' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('PARADA ORTEGA GUSTAVO ADOLFO') AND UPPER(TRIM(area)) = UPPER('LOGISTICA DESPOSTE');
-- MAYO: GUERRERO GUERRERO JOSE RODRIGO / PTAR -> 02/05/1999
UPDATE empleado SET fecha_nacimiento = '02/05/1999' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('GUERRERO GUERRERO JOSE RODRIGO') AND UPPER(TRIM(area)) = UPPER('PTAR');
-- MAYO: LOZADA ORTIZ TELMO / LOGISTICA -> 04/05/1987
UPDATE empleado SET fecha_nacimiento = '04/05/1987' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('LOZADA ORTIZ TELMO') AND UPPER(TRIM(area)) = UPPER('LOGISTICA');
-- MAYO: LEAL MARCHAN JESUS MIGUEL / SUBPRODUCTOS COMESTIBLES -> 05/05/1991
UPDATE empleado SET fecha_nacimiento = '05/05/1991' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('LEAL MARCHAN JESUS MIGUEL') AND UPPER(TRIM(area)) = UPPER('SUBPRODUCTOS COMESTIBLES');
-- MAYO: RINCON BOTELLO YERSON JAVIER / SUBPRODUCTOS COMESTIBLES -> 05/05/1989
UPDATE empleado SET fecha_nacimiento = '05/05/1989' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('RINCON BOTELLO YERSON JAVIER') AND UPPER(TRIM(area)) = UPPER('SUBPRODUCTOS COMESTIBLES');
-- MAYO: PARADA SIERRA FABIO ENRIQUE / LINEA DE SACRIFICIO -> 07/05/1996
UPDATE empleado SET fecha_nacimiento = '07/05/1996' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('PARADA SIERRA FABIO ENRIQUE') AND UPPER(TRIM(area)) = UPPER('LINEA DE SACRIFICIO');
-- MAYO: AMADOR SUAN SIXTO / SUBPRODUCTOS COMESTIBLES -> 07/05/1968
UPDATE empleado SET fecha_nacimiento = '07/05/1968' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('AMADOR SUAN SIXTO') AND UPPER(TRIM(area)) = UPPER('SUBPRODUCTOS COMESTIBLES');
-- MAYO: OSORIO ZANDUA JUAN SEBASTIAN / GESTION HUMANA -> 09/05/1995
UPDATE empleado SET fecha_nacimiento = '09/05/1995' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('OSORIO ZANDUA JUAN SEBASTIAN') AND UPPER(TRIM(area)) = UPPER('GESTION HUMANA');
-- MAYO: BETANCURT AGUDELO LUZ JASMIN / SUBPRODUCTOS COMESTIBLES -> 10/05/1977
UPDATE empleado SET fecha_nacimiento = '10/05/1977' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('BETANCURT AGUDELO LUZ JASMIN') AND UPPER(TRIM(area)) = UPPER('SUBPRODUCTOS COMESTIBLES');
-- MAYO: ARDILA PARRA JOAO CARLOS / LINEA DESPOSTE -> 11/05/1985
UPDATE empleado SET fecha_nacimiento = '11/05/1985' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('ARDILA PARRA JOAO CARLOS') AND UPPER(TRIM(area)) = UPPER('LINEA DESPOSTE');
-- MAYO: CRUZ QUIROGA MAYKIN ALIRIO / LOGISTICA -> 12/05/1984
UPDATE empleado SET fecha_nacimiento = '12/05/1984' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('CRUZ QUIROGA MAYKIN ALIRIO') AND UPPER(TRIM(area)) = UPPER('LOGISTICA');
-- MAYO: CAMACHO DIAZ DIEGO / LINEA DE SACRIFICIO -> 12/05/1992
UPDATE empleado SET fecha_nacimiento = '12/05/1992' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('CAMACHO DIAZ DIEGO') AND UPPER(TRIM(area)) = UPPER('LINEA DE SACRIFICIO');
-- MAYO: HIGUERA JAIMES ADRIANA LICETH / CALIDAD DESPOSTE -> 14/05/2003
UPDATE empleado SET fecha_nacimiento = '14/05/2003' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('HIGUERA JAIMES ADRIANA LICETH') AND UPPER(TRIM(area)) = UPPER('CALIDAD DESPOSTE');
-- MAYO: SOLANO GOMEZ VICTOR ALFONSO / LINEA DESPOSTE -> 17/05/1985
UPDATE empleado SET fecha_nacimiento = '17/05/1985' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('SOLANO GOMEZ VICTOR ALFONSO') AND UPPER(TRIM(area)) = UPPER('LINEA DESPOSTE');
-- MAYO: MOGOLLON HERRENO JHON FREDY / LINEA DE SACRIFICIO -> 17/05/1991
UPDATE empleado SET fecha_nacimiento = '17/05/1991' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('MOGOLLON HERRENO JHON FREDY') AND UPPER(TRIM(area)) = UPPER('LINEA DE SACRIFICIO');
-- MAYO: CALA CARVAJAL JAIDER ASDRUVAL / LOGISTICA -> 19/05/2003
UPDATE empleado SET fecha_nacimiento = '19/05/2003' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('CALA CARVAJAL JAIDER ASDRUVAL') AND UPPER(TRIM(area)) = UPPER('LOGISTICA');
-- MAYO: RENGIFO MORA OSCAR ALEJANDRO / SUBPRODUCTOS COMESTIBLES -> 19/05/1985
UPDATE empleado SET fecha_nacimiento = '19/05/1985' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('RENGIFO MORA OSCAR ALEJANDRO') AND UPPER(TRIM(area)) = UPPER('SUBPRODUCTOS COMESTIBLES');
-- MAYO: DIAZ VILLAMIZAR JAVIER ESTEVEN / SUBPRODUCTOS COMESTIBLES -> 22/05/2000
UPDATE empleado SET fecha_nacimiento = '22/05/2000' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('DIAZ VILLAMIZAR JAVIER ESTEVEN') AND UPPER(TRIM(area)) = UPPER('SUBPRODUCTOS COMESTIBLES');
-- MAYO: CARDENAS CARDENAS CARLOS ANDRES / PTAR -> 23/05/2002
UPDATE empleado SET fecha_nacimiento = '23/05/2002' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('CARDENAS CARDENAS CARLOS ANDRES') AND UPPER(TRIM(area)) = UPPER('PTAR');
-- MAYO: RAMIREZ VARGAS OLINTO / LINEA DE SACRIFICIO -> 23/05/1965
UPDATE empleado SET fecha_nacimiento = '23/05/1965' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('RAMIREZ VARGAS OLINTO') AND UPPER(TRIM(area)) = UPPER('LINEA DE SACRIFICIO');
-- MAYO: BONILLA BELTRAN SERGIO ANDRES / LINEA DE SACRIFICIO -> 26/05/1994
UPDATE empleado SET fecha_nacimiento = '26/05/1994' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('BONILLA BELTRAN SERGIO ANDRES') AND UPPER(TRIM(area)) = UPPER('LINEA DE SACRIFICIO');
-- MAYO: ROMERO URIBE ARNOL BRAN / LINEA DE SACRIFICIO -> 26/05/2005
UPDATE empleado SET fecha_nacimiento = '26/05/2005' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('ROMERO URIBE ARNOL BRAN') AND UPPER(TRIM(area)) = UPPER('LINEA DE SACRIFICIO');
-- MAYO: MOLINA RINCON LUIS MANUEL / LOGISTICA -> 26/05/1986
UPDATE empleado SET fecha_nacimiento = '26/05/1986' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('MOLINA RINCON LUIS MANUEL') AND UPPER(TRIM(area)) = UPPER('LOGISTICA');
-- MAYO: BUITRAGO MENDEZ ADRIANA ROCIO / DIRECCION DPTO CALIDAD -> 27/05/1999
UPDATE empleado SET fecha_nacimiento = '27/05/1999' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('BUITRAGO MENDEZ ADRIANA ROCIO') AND UPPER(TRIM(area)) = UPPER('DIRECCION DPTO CALIDAD');
-- MAYO: MANTILLA DELGADO LUIS ERNESTO / LINEA DE SACRIFICIO -> 28/05/1982
UPDATE empleado SET fecha_nacimiento = '28/05/1982' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('MANTILLA DELGADO LUIS ERNESTO') AND UPPER(TRIM(area)) = UPPER('LINEA DE SACRIFICIO');
-- MAYO: LOPEZ HURTADO ANDRES FABIAN / LINEA DE SACRIFICIO -> 29/05/1988
UPDATE empleado SET fecha_nacimiento = '29/05/1988' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('LOPEZ HURTADO ANDRES FABIAN') AND UPPER(TRIM(area)) = UPPER('LINEA DE SACRIFICIO');
-- MAYO: FERNANDEZ LUNA ALEXANDER / RECEPCION Y PESAJE -> 29/05/1977
UPDATE empleado SET fecha_nacimiento = '29/05/1977' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('FERNANDEZ LUNA ALEXANDER') AND UPPER(TRIM(area)) = UPPER('RECEPCION Y PESAJE');
-- MAYO: VARGAS DURAN ROBINSON / PRODUCCION DESPOSTE -> 31/05/1975
UPDATE empleado SET fecha_nacimiento = '31/05/1975' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('VARGAS DURAN ROBINSON') AND UPPER(TRIM(area)) = UPPER('PRODUCCION DESPOSTE');
-- JUNIO: VILLALBA ORTEGA JOHAN FERNANDO / LINEA DESPOSTE -> 01/06/2000
UPDATE empleado SET fecha_nacimiento = '01/06/2000' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('VILLALBA ORTEGA JOHAN FERNANDO') AND UPPER(TRIM(area)) = UPPER('LINEA DESPOSTE');
-- JUNIO: AGUDELO SAJONERO JHONATAN / LOGISTICA -> 01/06/2000
UPDATE empleado SET fecha_nacimiento = '01/06/2000' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('AGUDELO SAJONERO JHONATAN') AND UPPER(TRIM(area)) = UPPER('LOGISTICA');
-- JUNIO: ANGARITA CASTILLO HERSON DAVID / PORCIONADO -> 02/06/1986
UPDATE empleado SET fecha_nacimiento = '02/06/1986' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('ANGARITA CASTILLO HERSON DAVID') AND UPPER(TRIM(area)) = UPPER('PORCIONADO');
-- JUNIO: BOTHIA CARDENAS OMAR STEBEN / LOGISTICA -> 04/06/2003
UPDATE empleado SET fecha_nacimiento = '04/06/2003' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('BOTHIA CARDENAS OMAR STEBEN') AND UPPER(TRIM(area)) = UPPER('LOGISTICA');
-- JUNIO: HOYOS NIÑO ANDRES FELIPE / LINEA DE SACRIFICIO -> 05/06/2001
UPDATE empleado SET fecha_nacimiento = '05/06/2001' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('HOYOS NIÑO ANDRES FELIPE') AND UPPER(TRIM(area)) = UPPER('LINEA DE SACRIFICIO');
-- JUNIO: SERRANO ARDILA DIEGO FERNANDO / DIRECCION ADMON Y FINANCIERA -> 06/06/1978
UPDATE empleado SET fecha_nacimiento = '06/06/1978' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('SERRANO ARDILA DIEGO FERNANDO') AND UPPER(TRIM(area)) = UPPER('DIRECCION ADMON Y FINANCIERA');
-- JUNIO: PEÑA PEÑA LUIS DAVID / SUBPRODUCTOS COMESTIBLES -> 06/06/1998
UPDATE empleado SET fecha_nacimiento = '06/06/1998' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('PEÑA PEÑA LUIS DAVID') AND UPPER(TRIM(area)) = UPPER('SUBPRODUCTOS COMESTIBLES');
-- JUNIO: GUERRERO RAMOS LUIS DAVID / SUBPRODUCTOS COMESTIBLES -> 07/06/1995
UPDATE empleado SET fecha_nacimiento = '07/06/1995' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('GUERRERO RAMOS LUIS DAVID') AND UPPER(TRIM(area)) = UPPER('SUBPRODUCTOS COMESTIBLES');
-- JUNIO: ROJAS GUTIERREZ JHON FREDY / SUBPRODUCTOS COMESTIBLES -> 08/06/1993
UPDATE empleado SET fecha_nacimiento = '08/06/1993' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('ROJAS GUTIERREZ JHON FREDY') AND UPPER(TRIM(area)) = UPPER('SUBPRODUCTOS COMESTIBLES');
-- JUNIO: BOTHIA RAMIREZ OMAR / SUBPRODUCTOS COMESTIBLES -> 08/06/1978
UPDATE empleado SET fecha_nacimiento = '08/06/1978' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('BOTHIA RAMIREZ OMAR') AND UPPER(TRIM(area)) = UPPER('SUBPRODUCTOS COMESTIBLES');
-- JUNIO: RUEDA MADERO PAOLA CAROLINA / DIRECCION DPTO COMERCIAL -> 11/06/1988
UPDATE empleado SET fecha_nacimiento = '11/06/1988' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('RUEDA MADERO PAOLA CAROLINA') AND UPPER(TRIM(area)) = UPPER('DIRECCION DPTO COMERCIAL');
-- JUNIO: CORTES NIÑO YENSON ERNESTO / LINEA DE SACRIFICIO -> 12/06/1977
UPDATE empleado SET fecha_nacimiento = '12/06/1977' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('CORTES NIÑO YENSON ERNESTO') AND UPPER(TRIM(area)) = UPPER('LINEA DE SACRIFICIO');
-- JUNIO: CALDERON LOPEZ CAROL YULIANA / INVIMA -> 13/06/2002
UPDATE empleado SET fecha_nacimiento = '13/06/2002' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('CALDERON LOPEZ CAROL YULIANA') AND UPPER(TRIM(area)) = UPPER('INVIMA');
-- JUNIO: BARRIOS RUIZ MIGUEL ANGEL / LOGISTICA -> 13/06/1993
UPDATE empleado SET fecha_nacimiento = '13/06/1993' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('BARRIOS RUIZ MIGUEL ANGEL') AND UPPER(TRIM(area)) = UPPER('LOGISTICA');
-- JUNIO: BOLAÑO ALVAREZ HERNAN JOSE / LINEA DE SACRIFICIO -> 17/06/1995
UPDATE empleado SET fecha_nacimiento = '17/06/1995' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('BOLAÑO ALVAREZ HERNAN JOSE') AND UPPER(TRIM(area)) = UPPER('LINEA DE SACRIFICIO');
-- JUNIO: BOHORQUEZ ANGARITA ANDRES FELIPE / L&D DESPOSTE -> 22/06/1999
UPDATE empleado SET fecha_nacimiento = '22/06/1999' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('BOHORQUEZ ANGARITA ANDRES FELIPE') AND UPPER(TRIM(area)) = UPPER('L&D DESPOSTE');
-- JUNIO: JAIMES JAIMES FEDERICO / LINEA DE SACRIFICIO -> 21/06/1969
UPDATE empleado SET fecha_nacimiento = '21/06/1969' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('JAIMES JAIMES FEDERICO') AND UPPER(TRIM(area)) = UPPER('LINEA DE SACRIFICIO');
-- JUNIO: BAUTISTA CRUZ JOSE DANIEL / LIMPIEZA Y DESINFECCION -> 23/06/1997
UPDATE empleado SET fecha_nacimiento = '23/06/1997' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('BAUTISTA CRUZ JOSE DANIEL') AND UPPER(TRIM(area)) = UPPER('LIMPIEZA Y DESINFECCION');
-- JUNIO: ROJAS BARRERA CAMILO ANDRES / MERCADEO -> 24/06/1988
UPDATE empleado SET fecha_nacimiento = '24/06/1988' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('ROJAS BARRERA CAMILO ANDRES') AND UPPER(TRIM(area)) = UPPER('MERCADEO');
-- JUNIO: ANAYA LANDAZABAL SERGIO ANDRES / LOGISTICA -> 24/06/1985
UPDATE empleado SET fecha_nacimiento = '24/06/1985' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('ANAYA LANDAZABAL SERGIO ANDRES') AND UPPER(TRIM(area)) = UPPER('LOGISTICA');
-- JUNIO: BECERRA JAIMES DIEGO ARMANDO / LINEA DE SACRIFICIO -> 27/06/1992
UPDATE empleado SET fecha_nacimiento = '27/06/1992' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('BECERRA JAIMES DIEGO ARMANDO') AND UPPER(TRIM(area)) = UPPER('LINEA DE SACRIFICIO');
-- JUNIO: VILLAMIZAR RODRIGUEZ IVAN / SUBPRODUCTOS COMESTIBLES -> 27/06/1988
UPDATE empleado SET fecha_nacimiento = '27/06/1988' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('VILLAMIZAR RODRIGUEZ IVAN') AND UPPER(TRIM(area)) = UPPER('SUBPRODUCTOS COMESTIBLES');
-- JUNIO: CONDE VILLAMIZAR YENNIFER ROCIO / TESORERIA -> 28/06/2001
UPDATE empleado SET fecha_nacimiento = '28/06/2001' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('CONDE VILLAMIZAR YENNIFER ROCIO') AND UPPER(TRIM(area)) = UPPER('TESORERIA');
-- JUNIO: LOPEZ ARIZA PEDRO ANTONIO / RECEPCION Y PESAJE -> 29/06/1983
UPDATE empleado SET fecha_nacimiento = '29/06/1983' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('LOPEZ ARIZA PEDRO ANTONIO') AND UPPER(TRIM(area)) = UPPER('RECEPCION Y PESAJE');
-- JUNIO: RINCON DIAZ MILTON YESID / LOGISTICA -> 10/06/2000
UPDATE empleado SET fecha_nacimiento = '10/06/2000' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('RINCON DIAZ MILTON YESID') AND UPPER(TRIM(area)) = UPPER('LOGISTICA');
-- JUNIO: ANTON RODRIGUEZ HECTOR LUIS / SUBPRODUCTOS COMESTIBLES -> 16/06/1984
UPDATE empleado SET fecha_nacimiento = '16/06/1984' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('ANTON RODRIGUEZ HECTOR LUIS') AND UPPER(TRIM(area)) = UPPER('SUBPRODUCTOS COMESTIBLES');
-- JUNIO: ROJAS HERNANDEZ JUAN CARLOS / LINEA DE SACRIFICIO -> 04/06/1991
UPDATE empleado SET fecha_nacimiento = '04/06/1991' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('ROJAS HERNANDEZ JUAN CARLOS') AND UPPER(TRIM(area)) = UPPER('LINEA DE SACRIFICIO');
-- JUNIO: RUEDA PARRA EDWIN ORLANDO / SUBPRODUCTOS COMESTIBLES -> 22/06/1989
UPDATE empleado SET fecha_nacimiento = '22/06/1989' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('RUEDA PARRA EDWIN ORLANDO') AND UPPER(TRIM(area)) = UPPER('SUBPRODUCTOS COMESTIBLES');
-- JUNIO: SOTELO TORCEDILLA ROBINSON / RECEPCION Y PESAJE -> 23/06/1982
UPDATE empleado SET fecha_nacimiento = '23/06/1982' WHERE estado = 'ACTIVO' AND UPPER(TRIM(apellidos_nombre)) = UPPER('SOTELO TORCEDILLA ROBINSON') AND UPPER(TRIM(area)) = UPPER('RECEPCION Y PESAJE');

COMMIT;
