-- Unifica nombres viejos de area en empleado/retirado con el catálogo actual.
-- Ejecutar: python database/aplicar_sql_file.py database/sincronizar_areas_legacy.sql

USE gestio_humana;

-- TIC´s / TICS -> TECNOLOGIA
UPDATE empleado SET area = 'TECNOLOGIA'
WHERE UPPER(REPLACE(REPLACE(REPLACE(TRIM(area), '''', ''), '´', ''), '.', '')) IN ('TICS', 'TIC')
  AND area <> 'TECNOLOGIA';
UPDATE retirado SET area = 'TECNOLOGIA'
WHERE UPPER(REPLACE(REPLACE(REPLACE(TRIM(area), '''', ''), '´', ''), '.', '')) IN ('TICS', 'TIC')
  AND area <> 'TECNOLOGIA';

-- GERENCIA CALIDAD -> DIRECCION DPTO CALIDAD
UPDATE empleado SET area = 'DIRECCION DPTO CALIDAD' WHERE UPPER(TRIM(area)) = 'GERENCIA CALIDAD';
UPDATE retirado SET area = 'DIRECCION DPTO CALIDAD' WHERE UPPER(TRIM(area)) = 'GERENCIA CALIDAD';

-- PLANILLAJE Y FACTURACION / CARTERA -> TESORERIA
UPDATE empleado SET area = 'TESORERIA'
WHERE UPPER(TRIM(area)) IN ('PLANILLAJE Y FACTURACION', 'PLANILLAJE', 'CARTERA')
  AND area <> 'TESORERIA';
UPDATE retirado SET area = 'TESORERIA'
WHERE UPPER(TRIM(area)) IN ('PLANILLAJE Y FACTURACION', 'PLANILLAJE', 'CARTERA')
  AND area <> 'TESORERIA';

-- DIRECCION CONTROLLER -> CONTROL INTERNO
UPDATE empleado SET area = 'CONTROL INTERNO'
WHERE UPPER(TRIM(area)) IN ('DIRECCION CONTROLLER', 'CONTROLLER')
  AND area <> 'CONTROL INTERNO';
UPDATE retirado SET area = 'CONTROL INTERNO'
WHERE UPPER(TRIM(area)) IN ('DIRECCION CONTROLLER', 'CONTROLLER')
  AND area <> 'CONTROL INTERNO';

-- DIRECCION SURTIDORES / SURTIDORES -> DIRECCION DPTO COMERCIAL
UPDATE empleado SET area = 'DIRECCION DPTO COMERCIAL'
WHERE UPPER(TRIM(area)) IN ('DIRECCION SURTIDORES', 'SURTIDORES')
  AND area <> 'DIRECCION DPTO COMERCIAL';
UPDATE retirado SET area = 'DIRECCION DPTO COMERCIAL'
WHERE UPPER(TRIM(area)) IN ('DIRECCION SURTIDORES', 'SURTIDORES')
  AND area <> 'DIRECCION DPTO COMERCIAL';

-- DATA -> TECNOLOGIA
UPDATE empleado SET area = 'TECNOLOGIA' WHERE UPPER(TRIM(area)) = 'DATA' AND area <> 'TECNOLOGIA';
UPDATE retirado SET area = 'TECNOLOGIA' WHERE UPPER(TRIM(area)) = 'DATA' AND area <> 'TECNOLOGIA';

-- PLANEACION Y PROYECTOS (nombre de depto usado como area) -> PLANEACION
UPDATE empleado SET area = 'PLANEACION' WHERE UPPER(TRIM(area)) = 'PLANEACION Y PROYECTOS';
UPDATE retirado SET area = 'PLANEACION' WHERE UPPER(TRIM(area)) = 'PLANEACION Y PROYECTOS';

-- DIRECCION OPERACIONES -> DIRECCION PRODUCCION
UPDATE empleado SET area = 'DIRECCION PRODUCCION'
WHERE UPPER(TRIM(area)) IN ('DIRECCION OPERACIONES', 'DIRECCION DE OPERACIONES')
  AND area <> 'DIRECCION PRODUCCION';
UPDATE retirado SET area = 'DIRECCION PRODUCCION'
WHERE UPPER(TRIM(area)) IN ('DIRECCION OPERACIONES', 'DIRECCION DE OPERACIONES')
  AND area <> 'DIRECCION PRODUCCION';

-- CONTROL DE PROCESOS -> DIRECCION DPTO CALIDAD
UPDATE empleado SET area = 'DIRECCION DPTO CALIDAD'
WHERE UPPER(TRIM(area)) = 'CONTROL DE PROCESOS' AND area <> 'DIRECCION DPTO CALIDAD';
UPDATE retirado SET area = 'DIRECCION DPTO CALIDAD'
WHERE UPPER(TRIM(area)) = 'CONTROL DE PROCESOS' AND area <> 'DIRECCION DPTO CALIDAD';

-- SST: crear en catálogo si falta (DPTO DE OPERACIONES)
INSERT INTO area (departamento_id, nombre)
SELECT d.id, 'SST'
FROM departamento d
WHERE UPPER(TRIM(d.nombre)) = 'DPTO DE OPERACIONES'
  AND NOT EXISTS (SELECT 1 FROM area a WHERE UPPER(TRIM(a.nombre)) = 'SST');
